idf_component_register(
    SRCS
        "main.c"
        "display.c"
        "ui.c"
        "anim_loader.c"
        "net_ws.c"
        "ble_prov.c"
        "ap_prov.c"
        "prov_cfg.c"
        "serial_cli.c"
        "btn_boot.c"
        "agent_cfg.c"
        "audio.c"
        "voice.c"
        "font_loader.c"
        "font_status_icons.c"
        "mem_utils.c"
        "ws_url.c"
        "ui_face.c"
    INCLUDE_DIRS "."
    REQUIRES
        driver
        esp_lcd
        esp_wifi
        esp_http_server
        esp_event
        esp_netif
        esp_timer
        nvs_flash
        bt
        json
        vfs
        esp_partition
        esp_psram
        lwip
        esp_driver_usb_serial_jtag
)
