#!/usr/bin/env python3
"""Generate LVGL CJK binary font for the cjk_font flash partition.

Outputs:
  firmware/data/font_cjk_16.bin  — flash payload (offset 0x400000)
  main/font_size.h               — FONT_CJK_BIN_SIZE
  main/font_cjk_16.h             — C API (loaded at runtime)

No longer embeds glyph data into the app image.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHARS_FILE = ROOT / "third_party" / "fonts" / "tyz_7000_chars.txt"
OUT_BIN = ROOT / "firmware" / "data" / "font_cjk_16.bin"
OUT_H = ROOT / "main" / "font_cjk_16.h"
OUT_SIZE_H = ROOT / "main" / "font_size.h"
TYZ_CHAR_COUNT = 7000
FONT_CANDIDATES = [
    Path("C:/Windows/Fonts/simhei.ttf"),
    Path("C:/Windows/Fonts/Deng.ttf"),
    Path("C:/Windows/Fonts/msyh.ttc"),
    Path("C:/Windows/Fonts/simsun.ttc"),
]

EXTRA_SYMBOLS = "。，、：；？！「」『』（）【】《》…—·￥"


def load_tyz_chars() -> str:
    text = CHARS_FILE.read_text(encoding="utf-8")
    chars = []
    seen = set()
    for ch in text:
        if ch.isspace():
            continue
        if ch not in seen:
            seen.add(ch)
            chars.append(ch)
    if len(chars) != TYZ_CHAR_COUNT:
        raise SystemExit(f"expected {TYZ_CHAR_COUNT} chars in {CHARS_FILE.name}, got {len(chars)}")
    return "".join(chars)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--size", type=int, default=16)
    parser.add_argument("--bpp", type=int, default=4)
    parser.add_argument("--font", type=Path, default=None)
    args = parser.parse_args()

    font_path = args.font or next((p for p in FONT_CANDIDATES if p.exists()), None)
    if font_path is None:
        print("Font not found:", ", ".join(str(p) for p in FONT_CANDIDATES), file=sys.stderr)
        return 1

    tyz_chars = load_tyz_chars()
    extra = "".join(dict.fromkeys(ch for ch in EXTRA_SYMBOLS if ch not in tyz_chars))
    symbols = extra + tyz_chars

    npx = shutil.which("npx") or shutil.which("npx.cmd")
    if not npx:
        print("npx not found", file=sys.stderr)
        return 1

    OUT_BIN.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        npx,
        "--yes",
        "lv_font_conv",
        "--size",
        str(args.size),
        "--bpp",
        str(args.bpp),
        "--format",
        "bin",
        "--no-compress",
        "--no-prefilter",
        "--no-kerning",
        "--font",
        str(font_path),
        "-r",
        "0x20-0x7F",
        "--symbols",
        symbols,
        "-o",
        str(OUT_BIN),
    ]
    print(f"font={font_path}")
    print(f"size={args.size} bpp={args.bpp} tyz={len(tyz_chars)} extra={len(extra)} ascii=0x20-0x7F")
    print("running lv_font_conv (bin) ...")
    subprocess.run(cmd, check=True)

    bin_size = OUT_BIN.stat().st_size
    max_part = 2 * 1024 * 1024
    if bin_size > max_part:
        raise SystemExit(f"font bin {bin_size} exceeds cjk_font partition {max_part}")

    OUT_SIZE_H.write_text(
        "#pragma once\n\n"
        f"/* Generated by scripts/gen_cjk_font.py — do not edit. */\n"
        f"#define FONT_CJK_BIN_SIZE {bin_size}u\n"
        f"#define FONT_CJK_PART_OFFSET 0x400000u\n"
        f"#define FONT_CJK_PART_SUBTYPE 0x99u\n",
        encoding="utf-8",
    )
    OUT_H.write_text(
        "#pragma once\n\n"
        "#include \"lvgl.h\"\n\n"
        "#include <stdbool.h>\n\n"
        "/** Load CJK font from cjk_font flash partition (call once before UI uses it). */\n"
        "bool font_cjk_init(void);\n\n"
        "/** Runtime font; NULL if partition missing / load failed. */\n"
        "const lv_font_t *font_cjk_get(void);\n",
        encoding="utf-8",
    )

    # Drop obsolete embedded C source if present (no longer linked).
    old_c = ROOT / "main" / "font_cjk_16.c"
    if old_c.exists():
        old_c.unlink()
        print(f"removed obsolete {old_c}")

    print(f"wrote {OUT_BIN} ({bin_size} bytes)")
    print(f"wrote {OUT_SIZE_H}")
    print(f"wrote {OUT_H}")
    print("Flash with: python scripts/flash_font.py -p COMx")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
